apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-service
  namespace: demo-gitops
spec:
  selector:
    app: nginx-demo
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
